[package]
name = "launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
reqwest = { version = "*", features = ["stream", "json"] }
tokio = { version = "*", features = ["full"] }
tokio-util = { version = "*", features = ["io"] }
anyhow = "*"
futures-util = "*"
chrono = { version = "*", features = ["serde"] }
